# Primer árbol de decisión con scikit-learn

In [12]:
# librerias requeridas
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
# cargar datos 
titanic = pd.read_csv("./dataset/titanic.csv")
titanic.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [14]:
# Eliminar columnas que no insiden en el modelo
columns_to_drop = ['Name', 'Fare']
titanic.drop(columns_to_drop, axis="columns", inplace=True)
titanic.head()

,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard
0,0,3,male,22.0,1,0
1,1,1,female,38.0,1,0
2,1,3,female,26.0,0,0
3,1,1,female,35.0,1,0
4,0,3,male,35.0,0,0

In [15]:
# renombrar las columnas
titanic.columns = ['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch']
titanic.head()

   Survived  Pclass     Sex   Age  SibSp  Parch
0         0       3    male  22.0      1      0
1         1       1  female  38.0      1      0
2         1       3  female  26.0      0      0
3         1       1  female  35.0      1      0
4         0       3    male  35.0      0      0

In [16]:
# Analizar el shape
print(titanic.shape)

(887, 6)

In [17]:
# visualizar tipo de datos
titanic.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
dtype: object

In [18]:
# tipos de datos apropiados
titanic = pd.get_dummies(titanic, columns=["Sex"], drop_first=True, dtype="uint8")
titanic.dtypes

Survived      int64
Pclass        int64
Age         float64
SibSp         int64
Parch         int64
Sex_male      uint8
dtype: object

In [19]:
titanic.head()

   Survived  Pclass   Age  SibSp  Parch  Sex_male
0         0       3  22.0      1      0         1
1         1       1  38.0      1      0         0
2         1       3  26.0      0      0         0
3         1       1  35.0      1      0         0
4         0       3  35.0      0      0         1

In [20]:
titanic.rename(columns={'Sex_male':'Sex'}, inplace=True)
titanic.head()

   Survived  Pclass   Age  SibSp  Parch  Sex
0         0       3  22.0      1      0    1
1         1       1  38.0      1      0    0
2         1       3  26.0      0      0    0
3         1       1  35.0      1      0    0
4         0       3  35.0      0      0    1

In [21]:
# Ordenar las columnas
titanic = titanic[['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch']]
titanic.head()

   Survived  Pclass  Sex   Age  SibSp  Parch
0         0       3    1  22.0      1      0
1         1       1    0  38.0      1      0
2         1       3    0  26.0      0      0
3         1       1    0  35.0      1      0
4         0       3    1  35.0      0      0

In [ ]:
# clase 4